services:
  db:
    image: mysql:8.0.42
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mysql-config/my.cnf:/etc/mysql/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 1G