version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
    network_mode: host
    restart: always
    depends_on:
      - db
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      network: host
    network_mode: host
    depends_on:
      - app
  
  db:
    build:
      network: host
    image: mysql/mysql-server:latest
    network_mode: host
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=root
    # ports:
    #   - '3306:3306'
